<a href="https://colab.research.google.com/github/dravidshankar/Data-Science-using-Azure-GD-Goenka/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
A =np.array([[11,22],[33,44],[55,66]])
A

array([[11, 22],
       [33, 44],
       [55, 66]])

In [ ]:
#Calculate the mean of each column
Mean = np.mean(A.T,axis=1)

In [ ]:
Mean

array([33., 44.])

In [ ]:
#Subtract Mean from columns of original matrix
C = A-Mean

In [ ]:
C

array([[-22., -22.],
       [  0.,   0.],
       [ 22.,  22.]])

In [ ]:
#Calculate the covariance of the C matrix
V = np.cov(C.T)

In [ ]:
#Covariance
V

array([[484., 484.],
       [484., 484.]])

In [ ]:
#Eigen Value Decomposition
e_values,e_vectors = np.linalg.eig(V)

In [ ]:
#Print Eigen Values and Eigen Vectors
print("Eigen Values:",e_values,"Eigen Vectors:",e_vectors)

Eigen Values: [968.   0.] Eigen Vectors: [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [ ]:
#Project Data
P = e_vectors.T.dot(C.T)

In [ ]:
P

array([[-3.11126984e+01,  0.00000000e+00,  3.11126984e+01],
       [-8.88178420e-16,  0.00000000e+00,  8.88178420e-16]])

In [ ]:
P.T

array([[-3.11126984e+01, -8.88178420e-16],
       [ 0.00000000e+00,  0.00000000e+00],
       [ 3.11126984e+01,  8.88178420e-16]])

In [ ]:
C

array([[-22., -22.],
       [  0.,   0.],
       [ 22.,  22.]])

In [ ]:
#SKLEARN PCA
from sklearn.decomposition import PCA

In [ ]:
A

array([[11, 22],
       [33, 44],
       [55, 66]])

In [ ]:
#Calculate PCA
pca = PCA(2)

In [ ]:
pca.fit(A)

PCA(n_components=2)

In [ ]:
pca.components_

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [ ]:
New_data = pca.transform(A)

In [ ]:
New_data

array([[ 3.11126984e+01, -3.33066907e-15],
       [ 0.00000000e+00,  0.00000000e+00],
       [-3.11126984e+01,  3.33066907e-15]])

In [ ]:
P.T

array([[-3.11126984e+01, -8.88178420e-16],
       [ 0.00000000e+00,  0.00000000e+00],
       [ 3.11126984e+01,  8.88178420e-16]])